name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.8.x

      # Step 1: Get OAuth Access Token from Azure AD
      - name: Get Azure AD OAuth Token
        id: oauth
        run: |
          TOKEN=$(curl -X POST ${{ secrets.AZURE_TOKEN_ENDPOINT }} \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" \
            -d "scope=${{ secrets.APPLICATION_ID }}/.default" \
            | jq -r .access_token)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange using OAuth Token
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USER: ${{ secrets.SF_USER }}       # Mapped SSO login
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          OAUTH_TOKEN: ${{ steps.oauth.outputs.token }}
        run: |
          schemachange \
            -f $GITHUB_WORKSPACE/migrations \
            -a $SF_ACCOUNT \
            -u $SF_USER \
            --authenticator oauth \
            --token $OAUTH_TOKEN \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
